### ISSUE TITLE
Unknown function: Flake8

### ISSUE THREAD

**Issue by cobhimself** [nvie/vim-flake8#13]
When utilizing the following command to run Flake8 on save, I get an "Unknown function: Flake8" error. The plugin still works, and >> is displayed next to the lines where there are errors but it's quite annoying.

Here is the code I'm using in my .vimrc file (suggested by the README):

```
autocmd BufWritePost *.py call Flake8()
```

I use Vundle instead of pathogen... not sure if that makes a difference. I'm on a Mac (OSX 10.6.8) using Mac Vim version 7.3. Any help would be appreciated! Thanks!

**Comment by talonx** [comment]
Faced the same problem on Ubuntu 15.04. The symlink suggestion worked for me.

**Comment by kwikiel** [comment]
trivial solution:
apt-get install flake8

**Comment by talonx** [comment]
@kwikiel That is not the solution. All of us have flake8 installed.

**Comment by Lukas0907** [comment]
Instead of symlinking ``plugin`` to ``ftplugin`` it's cleaner to add `` filetype plugin on`` to ``.vimrc``

**Comment by vanschelven** [comment]
I ended up here because I had an error message that precisely matched the one from this bug from 8 years ago. Given that, the underlying problem is likely different. Still, for future visitors the following may be relevant: 

As per https://github.com/nvie/vim-flake8/pull/77 the correct way to call the plugin is with `flake8#Flake8()` now. I have no idea since when this is the case (at least 2019, it appears) but it turned an existing config file into a buggy one when running a recent upgrade.
